export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export NODE_PATH="/usr/local/lib/node_modules"
export PGDATA="/usr/local/var/postgres"

[ -f "$HOME/.cargo/env" ] && source $HOME/.cargo/env

[ -f "/usr/local/etc/profile.d/z.sh" ] && source /usr/local/etc/profile.d/z.sh

