export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export NODE_PATH="/usr/local/lib/node_modules"
export PGDATA="/usr/local/var/postgres"

if [ -f "$HOME/.cargo/env" ]; then
    source $HOME/.cargo/env
fi

if [ -f "/usr/local/etc/profile.d/z.sh" ]; then
    source /usr/local/etc/profile.d/z.sh
fi
